# Generated by Django 3.0.7 on 2020-07-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbakuadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название текста')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Тексты',
                'verbose_name_plural': 'Тексты',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_name',
            field=models.SlugField(verbose_name='slug name(заполняется автоматически)'),
        ),
    ]
