# Generated by Django 3.0.7 on 2020-07-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbakuadmin', '0002_auto_20200701_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='slug_name',
            field=models.SlugField(null=True, verbose_name='slug name(заполняется автоматически)'),
        ),
    ]
