# Generated by Django 3.0.7 on 2020-07-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbakuadmin', '0003_text_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.CharField(default='ipa', max_length=64, verbose_name='Стиль'),
        ),
    ]
