# Generated by Django 3.0.7 on 2020-07-03 16:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbakuadmin', '0004_beer_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.CharField(default='ipa', max_length=128, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
    ]
