# Generated by Django 3.0.7 on 2020-07-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbakuadmin', '0005_auto_20200703_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Не за', verbose_name='Текст конкурса')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурс',
            },
        ),
        migrations.CreateModel(
            name='CasinoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('user_id', models.ImageField(upload_to='', verbose_name='ID')),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Участники конкурса',
                'verbose_name_plural': 'Участники конкурса',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=20)),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='Дата первого заказа')),
                ('last_date', models.DateField(auto_now=True, verbose_name='Дта последнего заказа')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
