# Generated by Django 3.0.7 on 2020-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbakuadmin', '0006_casino_casinouser_tguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='text',
            field=models.TextField(default='Не забудь, удалить всех пользователей из таблицы "Участиники конкурса", перед созданием новго конкурса', verbose_name='Текст конкурса'),
        ),
        migrations.AlterField(
            model_name='casinouser',
            name='user_id',
            field=models.IntegerField(verbose_name='ID'),
        ),
    ]
